"""initial schema

Revision ID: e43670afe39f
Revises: 
Create Date: 2026-10-10 11:36:27.665657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e43670afe39f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boundary_crosswalk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_pcode', sa.String(length=32), nullable=False),
    sa.Column('new_pcode', sa.String(length=32), nullable=False),
    sa.Column('population_share', sa.Float(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('old_pcode', 'new_pcode')
    )
    op.create_index(op.f('ix_boundary_crosswalk_new_pcode'), 'boundary_crosswalk', ['new_pcode'], unique=False)
    op.create_index(op.f('ix_boundary_crosswalk_old_pcode'), 'boundary_crosswalk', ['old_pcode'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('report_path', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_units',
    sa.Column('pcode', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=32), nullable=True),
    sa.Column('parent_pcode', sa.String(length=32), nullable=True),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('dhis2_uid', sa.String(length=11), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['parent_pcode'], ['org_units.pcode'], ),
    sa.PrimaryKeyConstraint('pcode'),
    sa.UniqueConstraint('dhis2_uid')
    )
    op.create_index(op.f('ix_org_units_level'), 'org_units', ['level'], unique=False)
    op.create_index(op.f('ix_org_units_name'), 'org_units', ['name'], unique=False)
    op.create_index(op.f('ix_org_units_parent_pcode'), 'org_units', ['parent_pcode'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pcode', sa.String(length=32), nullable=False),
    sa.Column('disease', sa.String(length=50), nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pcode'], ['org_units.pcode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_pcode'), 'alerts', ['pcode'], unique=False)
    op.create_index(op.f('ix_alerts_tier'), 'alerts', ['tier'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pcode', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('vaccine', sa.String(length=50), nullable=False),
    sa.Column('age_min_months', sa.Integer(), nullable=True),
    sa.Column('age_max_months', sa.Integer(), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pcode'], ['org_units.pcode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_pcode'), 'campaigns', ['pcode'], unique=False)
    op.create_table('immunization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pcode', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('mcv1_doses', sa.Integer(), nullable=True),
    sa.Column('mcv2_doses', sa.Integer(), nullable=True),
    sa.Column('births', sa.Integer(), nullable=True),
    sa.Column('mcv1_coverage', sa.Float(), nullable=True),
    sa.Column('mcv2_coverage', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pcode'], ['org_units.pcode'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pcode', 'year', 'month', 'source')
    )
    op.create_index(op.f('ix_immunization_pcode'), 'immunization', ['pcode'], unique=False)
    op.create_table('indicator_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pcode', sa.String(length=32), nullable=False),
    sa.Column('disease', sa.String(length=50), nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('suspected', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('reports_expected', sa.Integer(), nullable=True),
    sa.Column('reports_received', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pcode'], ['org_units.pcode'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pcode', 'disease', 'iso_year', 'iso_week', 'source')
    )
    op.create_index(op.f('ix_indicator_counts_disease'), 'indicator_counts', ['disease'], unique=False)
    op.create_index(op.f('ix_indicator_counts_pcode'), 'indicator_counts', ['pcode'], unique=False)
    op.create_table('org_unit_adjacency',
    sa.Column('a_pcode', sa.String(length=32), nullable=False),
    sa.Column('b_pcode', sa.String(length=32), nullable=False),
    sa.Column('shared_border_km', sa.Float(), nullable=True),
    sa.Column('centroid_distance_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['a_pcode'], ['org_units.pcode'], ),
    sa.ForeignKeyConstraint(['b_pcode'], ['org_units.pcode'], ),
    sa.PrimaryKeyConstraint('a_pcode', 'b_pcode')
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pcode', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('susceptibles', sa.Float(), nullable=True),
    sa.Column('reporting_rate', sa.Float(), nullable=True),
    sa.Column('p_eff', sa.Float(), nullable=True),
    sa.Column('importation_pressure', sa.Float(), nullable=True),
    sa.Column('risk_index', sa.Float(), nullable=True),
    sa.Column('factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['pcode'], ['org_units.pcode'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pcode', 'year', 'month', 'model_version')
    )
    op.create_index(op.f('ix_risk_scores_pcode'), 'risk_scores', ['pcode'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('cases', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('extracted', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analysis', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analysis_failed', sa.Boolean(), nullable=False),
    sa.Column('pcode', sa.String(length=32), nullable=True),
    sa.Column('geocode_confidence', sa.Float(), nullable=True),
    sa.Column('geocode_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('geocode_candidates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pcode'], ['org_units.pcode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_analysis_failed'), 'signals', ['analysis_failed'], unique=False)
    op.create_index(op.f('ix_signals_cluster_id'), 'signals', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_signals_pcode'), 'signals', ['pcode'], unique=False)
    op.create_index(op.f('ix_signals_source_type'), 'signals', ['source_type'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_source_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_pcode'), table_name='signals')
    op.drop_index(op.f('ix_signals_cluster_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_analysis_failed'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_risk_scores_pcode'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_table('org_unit_adjacency')
    op.drop_index(op.f('ix_indicator_counts_pcode'), table_name='indicator_counts')
    op.drop_index(op.f('ix_indicator_counts_disease'), table_name='indicator_counts')
    op.drop_table('indicator_counts')
    op.drop_index(op.f('ix_immunization_pcode'), table_name='immunization')
    op.drop_table('immunization')
    op.drop_index(op.f('ix_campaigns_pcode'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_alerts_tier'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_pcode'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_org_units_parent_pcode'), table_name='org_units')
    op.drop_index(op.f('ix_org_units_name'), table_name='org_units')
    op.drop_index(op.f('ix_org_units_level'), table_name='org_units')
    op.drop_table('org_units')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_boundary_crosswalk_old_pcode'), table_name='boundary_crosswalk')
    op.drop_index(op.f('ix_boundary_crosswalk_new_pcode'), table_name='boundary_crosswalk')
    op.drop_table('boundary_crosswalk')
    # ### end Alembic commands ###
